# Generated by Django 5.2.5 on 2026-09-18 07:25

import core.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_field_labels'),
        ('core', '0004_user_scope_user_user_scope_matches_company'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('want_approval', models.BooleanField(default=False)),
                ('approval_status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=20, verbose_name='Designation Code')),
                ('title', models.CharField(max_length=100, verbose_name='Designation Title')),
                ('description', models.TextField(blank=True)),
                ('rank_order', models.PositiveSmallIntegerField(default=1)),
                ('attendance_method', models.CharField(choices=[('qr_station', 'QR scanned at the station'), ('self', 'Self check-in'), ('not_required', 'Not required')], default='qr_station', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='designations', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
            ],
            options={
                'db_table': 'designation',
                'ordering': ['rank_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('want_approval', models.BooleanField(default=False)),
                ('approval_status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('employee_code', models.CharField(max_length=20, verbose_name='Employee Code')),
                ('photo', models.ImageField(blank=True, upload_to='employees/')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Middle Name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Last Name')),
                ('attendance_method', models.CharField(blank=True, choices=[('qr_station', 'QR scanned at the station'), ('self', 'Self check-in'), ('not_required', 'Not required')], max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('divorced', 'Divorced')], max_length=10)),
                ('nationality', models.CharField(blank=True, max_length=60)),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='Mobile Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('emergency_contact_person', models.CharField(blank=True, max_length=100)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('is_blocked', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='company.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='crew.designation')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
            ],
            options={
                'db_table': 'employee',
                'ordering': ['employee_code'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('station_scan', 'Scanned at the station'), ('self', 'Self check-in')], max_length=20)),
                ('punched_at', models.DateTimeField()),
                ('business_date', models.DateField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('qr_token_id', models.CharField(blank=True, max_length=64)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='company.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='devices.device')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='core.user')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='crew.employee')),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-punched_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('address_type', models.CharField(choices=[('uae', 'UAE address'), ('home_country', 'Home country address'), ('temporary', 'Temporary address')], max_length=20)),
                ('line1', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('line2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('building', models.CharField(blank=True, max_length=100, verbose_name='Building Name')),
                ('flat', models.CharField(blank=True, max_length=50, verbose_name='Flat / Room No')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20, verbose_name='Zip Code')),
                ('landlord_name', models.CharField(blank=True, max_length=100)),
                ('landlord_phone', models.CharField(blank=True, max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('is_current', models.BooleanField(default=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='company.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='crew.employee')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='company.state')),
            ],
            options={
                'db_table': 'employee_address',
                'ordering': ['employee', 'address_type'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeBlockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('action', models.CharField(choices=[('block', 'Blocked'), ('unblock', 'Unblocked')], max_length=10)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('effective_date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='block_log', to='crew.employee')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
            ],
            options={
                'db_table': 'employee_block_log',
                'ordering': ['-effective_date', '-created_on'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='company.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='crew.designation')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='crew.employee')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
            ],
            options={
                'db_table': 'employee_designation',
                'ordering': ['-from_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=30)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('visa_number', models.CharField(blank=True, max_length=30)),
                ('visa_expiry', models.DateField(blank=True, null=True)),
                ('emirates_id_number', models.CharField(blank=True, max_length=30)),
                ('emirates_id_expiry', models.DateField(blank=True, null=True)),
                ('labour_card_number', models.CharField(blank=True, max_length=30)),
                ('labour_card_expiry', models.DateField(blank=True, null=True)),
                ('salary_bank', models.CharField(blank=True, max_length=100)),
                ('salary_account', models.CharField(blank=True, max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='crew.employee')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
            ],
            options={
                'db_table': 'employee_detail',
            },
        ),
        migrations.AddIndex(
            model_name='designation',
            index=models.Index(fields=['company'], name='designation_company_277e4b_idx'),
        ),
        migrations.AddConstraint(
            model_name='designation',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_designation_code_per_company', violation_error_message='A designation with this code already exists.'),
        ),
        migrations.AddConstraint(
            model_name='designation',
            constraint=models.UniqueConstraint(fields=('company', 'title'), name='uniq_designation_title_per_company', violation_error_message='A designation with this title already exists.'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company'], name='employee_company_61ef14_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['branch'], name='employee_branch__5028d8_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['designation'], name='employee_designa_deed15_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('company', 'employee_code'), name='uniq_employee_code_per_company', violation_error_message='An employee with this code already exists.'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee', 'business_date'], name='attendance_employe_a3b520_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['business_date'], name='attendance_busines_a08125_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['branch', 'business_date'], name='attendance_branch__23e3b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(condition=models.Q(('qr_token_id', ''), _negated=True), fields=('qr_token_id',), name='uniq_attendance_qr_token', violation_error_message='That QR code has already been scanned.'),
        ),
        migrations.AddIndex(
            model_name='employeeaddress',
            index=models.Index(fields=['employee', 'address_type'], name='employee_ad_employe_4521bc_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeblocklog',
            index=models.Index(fields=['employee'], name='employee_bl_employe_d20ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='employeedesignation',
            index=models.Index(fields=['employee', 'to_date'], name='employee_de_employe_97d969_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeedesignation',
            constraint=models.UniqueConstraint(condition=models.Q(('to_date__isnull', True)), fields=('employee',), name='uniq_open_posting_per_employee', violation_error_message='This employee already has a current posting.'),
        ),
    ]
