# Generated by Django 5.2.5 on 2026-09-29 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_weekday_monday_zero'),
        ('core', '0005_user_employee'),
        ('crew', '0002_duty_roster'),
    ]

    # The old table never had a write path (no app posted to it), so it is
    # dropped and rebuilt rather than altered field by field.
    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('qr_scan', 'QR scanned'), ('self', 'Self attendance')], max_length=10)),
                ('punch_type', models.CharField(choices=[('punch_in', 'Punch in'), ('punch_out', 'Punch out')], max_length=10)),
                ('employee_code', models.CharField(max_length=20)),
                ('employee_name', models.CharField(max_length=150)),
                ('employee_installation_id', models.CharField(blank=True, max_length=64)),
                ('qr_generation_time', models.DateTimeField(blank=True, null=True)),
                ('employee_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('employee_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('rms_employee_code', models.CharField(blank=True, max_length=20)),
                ('rms_employee_name', models.CharField(blank=True, max_length=150)),
                ('rms_installation_id', models.CharField(max_length=64)),
                ('rms_scan_time', models.DateTimeField()),
                ('rms_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('rms_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='crew.employee')),
                ('employee_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='company.branch')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('punch_in', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='punch_out', to='crew.attendance')),
                ('rms_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_scanned', to='company.branch')),
                ('rms_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_scanned', to='crew.employee')),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-rms_scan_time'],
                'indexes': [models.Index(fields=['employee', 'rms_scan_time'], name='attendance_employe_a28794_idx'), models.Index(fields=['rms_scan_time'], name='attendance_rms_sca_09b73c_idx'), models.Index(fields=['employee_branch', 'rms_scan_time'], name='attendance_employe_5f7659_idx'), models.Index(fields=['rms_branch', 'rms_scan_time'], name='attendance_rms_bra_9a6305_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('qr_generation_time__isnull', False), ('rms_branch__isnull', False), ('rms_employee__isnull', False), ('source', 'qr_scan'), models.Q(('employee_installation_id', ''), _negated=True), models.Q(('rms_employee_code', ''), _negated=True)), models.Q(('employee_installation_id', ''), ('employee_latitude__isnull', True), ('qr_generation_time__isnull', True), ('rms_branch__isnull', True), ('rms_employee__isnull', True), ('rms_employee_code', ''), ('rms_employee_name', ''), ('source', 'self')), _connector='OR'), name='attendance_source_fields'), models.CheckConstraint(condition=models.Q(models.Q(('punch_in__isnull', True), ('punch_type', 'punch_in')), models.Q(('punch_in__isnull', False), ('punch_type', 'punch_out')), _connector='OR'), name='attendance_out_has_in'), models.UniqueConstraint(condition=models.Q(('source', 'qr_scan')), fields=('employee', 'qr_generation_time', 'punch_type'), name='uniq_attendance_qr_scan', violation_error_message='That QR code has already been scanned.'), models.CheckConstraint(condition=models.Q(models.Q(('employee_latitude__isnull', True), ('employee_longitude__isnull', True)), models.Q(('employee_latitude__isnull', False), ('employee_longitude__isnull', False)), _connector='OR'), name='attendance_employee_gps_pair'), models.CheckConstraint(condition=models.Q(('employee_latitude__isnull', True), models.Q(('employee_latitude__gte', -90), ('employee_latitude__lte', 90), ('employee_longitude__gte', -180), ('employee_longitude__lte', 180)), _connector='OR'), name='attendance_employee_gps_range'), models.CheckConstraint(condition=models.Q(models.Q(('rms_latitude__isnull', True), ('rms_longitude__isnull', True)), models.Q(('rms_latitude__isnull', False), ('rms_longitude__isnull', False)), _connector='OR'), name='attendance_rms_gps_pair'), models.CheckConstraint(condition=models.Q(('rms_latitude__isnull', True), models.Q(('rms_latitude__gte', -90), ('rms_latitude__lte', 90), ('rms_longitude__gte', -180), ('rms_longitude__lte', 180)), _connector='OR'), name='attendance_rms_gps_range')],
            },
        ),
    ]
