# Generated by Django 5.2.5 on 2026-10-05 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_paymentmode'),
        ('core', '0005_user_employee'),
        ('crew', '0003_attendance_redesign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='employee_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='company.branch'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.CheckConstraint(condition=models.Q(('source', 'self'), ('employee_branch__isnull', False), _connector='OR'), name='attendance_qr_has_employee_branch'),
        ),
    ]
