# Generated by Django 5.2.5 on 2026-09-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('core', '0003_user_role'),
        ('portal', '0004_seed_company_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scope',
            field=models.CharField(choices=[('company', 'One company'), ('system', 'Every company')], default='company', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('company__isnull', False), ('scope', 'company')), models.Q(('company__isnull', True), ('scope', 'system')), _connector='OR'), name='user_scope_matches_company'),
        ),
    ]
