# Generated by Django 5.2.5 on 2026-09-30 05:56

import apps.fare.db
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0008_weekday_monday_zero'),
        ('core', '0005_user_employee'),
        ('rental', '0001_initial'),
        # btree_gist, for card_discount_no_overlap's `=` on a plain column.
        ('fare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.CharField(max_length=20, verbose_name='Grade Code')),
                ('name', models.CharField(max_length=100, verbose_name='Grade Name')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_grades', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
            ],
            options={
                'verbose_name_plural': 'card grades',
                'db_table': 'card_grade',
                'ordering': ['card_type__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CardDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('valid_from', models.DateField(verbose_name='From Date')),
                ('valid_to', models.DateField(verbose_name='To Date')),
                ('requires_approval', models.BooleanField(default=False)),
                ('fare_basis', models.CharField(choices=[('base', 'Base Fare'), ('full', 'Full Fare')], max_length=4)),
                ('usage_type', models.CharField(choices=[('one_time', 'One time'), ('per_day', 'Times a day'), ('per_week', 'Times a week'), ('per_month', 'Times a month'), ('per_period', 'Times in the period')], max_length=10)),
                ('usage_limit', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_discounts', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('card_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='discount.cardgrade')),
            ],
            options={
                'verbose_name_plural': 'card discounts',
                'db_table': 'card_discount',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.CharField(max_length=20, verbose_name='Card Type Code')),
                ('name', models.CharField(max_length=100, verbose_name='Card Type Name')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_types', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
            ],
            options={
                'verbose_name_plural': 'card types',
                'db_table': 'card_type',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='cardgrade',
            name='card_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='discount.cardtype'),
        ),
        migrations.CreateModel(
            name='CardDiscountClaim',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Discount %')),
                ('fare_basis', models.CharField(choices=[('base', 'Base Fare'), ('full', 'Full Fare')], max_length=4)),
                ('requires_approval', models.BooleanField()),
                ('customer_name', models.CharField(max_length=200)),
                ('mobile_full', models.CharField(max_length=30, verbose_name='Phone')),
                ('card_number', models.CharField(blank=True, max_length=50)),
                ('card_photo', models.CharField(blank=True, max_length=255)),
                ('order_ref', models.CharField(blank=True, max_length=64, verbose_name='Order')),
                ('bill_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rms_installation_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('redeemed', 'Redeemed')], max_length=10)),
                ('requested_at', models.DateTimeField()),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='card_claims', to='company.branch')),
                ('card_discount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='discount.carddiscount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_claims', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_claims', to='rental.customer')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('card_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='discount.cardgrade')),
                ('card_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='discount.cardtype')),
            ],
            options={
                'db_table': 'card_discount_claim',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='CardDiscountDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Discount %')),
                ('card_discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='discount.carddiscount')),
            ],
            options={
                'db_table': 'card_discount_day',
                'ordering': ['weekday'],
                'constraints': [models.UniqueConstraint(fields=('card_discount', 'weekday'), name='uniq_card_discount_day'), models.CheckConstraint(condition=models.Q(('discount_percent__gt', 0), ('discount_percent__lte', 100)), name='card_discount_day_percent'), models.CheckConstraint(condition=models.Q(('weekday__lte', 6)), name='card_discount_day_weekday')],
            },
        ),
        migrations.AddIndex(
            model_name='carddiscount',
            index=models.Index(fields=['company'], name='card_discou_company_857903_idx'),
        ),
        migrations.AddIndex(
            model_name='carddiscount',
            index=models.Index(fields=['card_grade'], name='card_discou_card_gr_65c5a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='carddiscount',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__gte', models.F('valid_from'))), name='card_discount_dates'),
        ),
        migrations.AddConstraint(
            model_name='carddiscount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('usage_limit__isnull', True), ('usage_type', 'one_time')), models.Q(models.Q(('usage_type', 'one_time'), _negated=True), ('usage_limit__gte', 1), ('usage_limit__isnull', False)), _connector='OR'), name='card_discount_usage_limit'),
        ),
        migrations.AddConstraint(
            model_name='carddiscount',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('is_active', True)), expressions=[('card_grade', '='), (apps.fare.db.DateRangeFunc('valid_from', 'valid_to', django.contrib.postgres.fields.ranges.RangeBoundary(inclusive_lower=True, inclusive_upper=True)), '&&')], name='card_discount_no_overlap', violation_error_message='Another active discount covers these dates for this grade.'),
        ),
        migrations.AddIndex(
            model_name='cardtype',
            index=models.Index(fields=['company'], name='card_type_company_66eeae_idx'),
        ),
        migrations.AddConstraint(
            model_name='cardtype',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_card_type_code', violation_error_message='A card type with this code already exists.'),
        ),
        migrations.AddConstraint(
            model_name='cardtype',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_card_type_name', violation_error_message='A card type with this name already exists.'),
        ),
        migrations.AddIndex(
            model_name='cardgrade',
            index=models.Index(fields=['company'], name='card_grade_company_67d3eb_idx'),
        ),
        migrations.AddIndex(
            model_name='cardgrade',
            index=models.Index(fields=['card_type'], name='card_grade_card_ty_63aa8a_idx'),
        ),
        migrations.AddConstraint(
            model_name='cardgrade',
            constraint=models.UniqueConstraint(fields=('card_type', 'code'), name='uniq_card_grade_code', violation_error_message='This card type already has a grade with this code.'),
        ),
        migrations.AddConstraint(
            model_name='cardgrade',
            constraint=models.UniqueConstraint(fields=('card_type', 'name'), name='uniq_card_grade_name', violation_error_message='This card type already has a grade with this name.'),
        ),
        migrations.AddIndex(
            model_name='carddiscountclaim',
            index=models.Index(fields=['status', 'requested_at'], name='card_discou_status_cc6553_idx'),
        ),
        migrations.AddIndex(
            model_name='carddiscountclaim',
            index=models.Index(fields=['customer', 'card_discount', 'redeemed_at'], name='card_discou_custome_125bd6_idx'),
        ),
        migrations.AddIndex(
            model_name='carddiscountclaim',
            index=models.Index(fields=['company', 'requested_at'], name='card_discou_company_fb66f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='carddiscountclaim',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__gt', 0), ('discount_percent__lte', 100)), name='card_claim_percent'),
        ),
        migrations.AddConstraint(
            model_name='carddiscountclaim',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decided_at__isnull', True), ('decided_by__isnull', True), ('redeemed_at__isnull', True), ('requires_approval', True), ('status', 'pending')), models.Q(('decided_at__isnull', False), ('redeemed_at__isnull', True), ('requires_approval', True), ('status__in', ['approved', 'rejected'])), models.Q(('redeemed_at__isnull', False), ('requires_approval', False), ('status', 'redeemed')), models.Q(('decided_at__isnull', False), ('redeemed_at__isnull', False), ('requires_approval', True), ('status', 'redeemed')), _connector='OR'), name='card_claim_status_fields'),
        ),
    ]
