# Generated by Django 5.2.5 on 2026-09-30 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_paymentmode'),
        ('core', '0005_user_employee'),
        ('discount', '0001_initial'),
        ('rental', '0004_order_payment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='carddiscountclaim',
            name='card_claim_status_fields',
        ),
        migrations.RemoveField(
            model_name='carddiscountclaim',
            name='order_ref',
        ),
        migrations.AddField(
            model_name='carddiscountclaim',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='carddiscountclaim',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='carddiscountclaim',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='card_claims', to='rental.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carddiscountclaim',
            name='card_photo',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='carddiscountclaim',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('redeemed', 'Redeemed')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='carddiscountclaim',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decided_at__isnull', True), ('decided_by__isnull', True), ('redeemed_at__isnull', True), ('requires_approval', True), ('status', 'pending')), models.Q(('decided_at__isnull', False), ('redeemed_at__isnull', True), ('requires_approval', True), ('status__in', ['approved', 'rejected'])), models.Q(('decided_at__isnull', False), ('redeemed_at__isnull', True), ('requires_approval', True), ('status', 'cancelled')), models.Q(('redeemed_at__isnull', False), ('requires_approval', False), ('status', 'redeemed')), models.Q(('decided_at__isnull', False), ('redeemed_at__isnull', False), ('requires_approval', True), ('status', 'redeemed')), _connector='OR'), name='card_claim_status_fields'),
        ),
        migrations.AddConstraint(
            model_name='carddiscountclaim',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('order',), name='uniq_pending_claim_per_order', violation_error_message='This order already has a pending approval request.'),
        ),
    ]
