# Generated by Django 5.2.5 on 2026-10-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_claim_order_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddiscountclaim',
            name='bill_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='carddiscountclaim',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='carddiscountclaim',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
    ]
