# Generated by Django 5.2.5 on 2026-09-17 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('core', '0003_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('web', 'Back office web'), ('operator', 'RMS operator app'), ('manager', 'Manager app'), ('employee', 'Employee app')], max_length=16)),
                ('version', models.CharField(max_length=20)),
                ('is_minimum_supported', models.BooleanField(default=False)),
                ('released_at', models.DateTimeField()),
                ('download_url', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'app_release',
                'ordering': ['channel', '-released_at'],
                'constraints': [models.UniqueConstraint(fields=('channel', 'version'), name='uniq_channel_version')],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('device_uid', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('channel', models.CharField(choices=[('web', 'Back office web'), ('operator', 'RMS operator app'), ('manager', 'Manager app'), ('employee', 'Employee app')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Awaiting approval'), ('approved', 'Approved'), ('blocked', 'Blocked'), ('retired', 'Retired')], default='pending', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='company.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
            ],
            options={
                'db_table': 'device',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceTrust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusts', to='devices.device')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_trusts', to='core.user')),
            ],
            options={
                'db_table': 'device_trust',
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['company'], name='device_company_a4e0e9_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['branch'], name='device_branch__c372fd_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetrust',
            index=models.Index(fields=['user'], name='device_trus_user_id_8a37c7_idx'),
        ),
    ]
