"""Last known position of a tablet.

Fed by the latitude/longitude the app already sends in its credentials block on
the registration and update-check calls, and overwritten each time -- a trail of
positions belongs to the tracking module, not here.

The legacy carried these on SfaDeviceMapping, where they recorded where an
operator stood at login rather than anything about the mapping itself. A
station's own coordinates are on Branch.
"""

# Generated by Django 5.2.5 on 2026-09-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_drop_device_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_location_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
