"""Per-station tablet configuration, replacing SfaDeviceSetting.

One active row per branch is a database rule here; the legacy kept it only in
its screen. See the DeviceSettings docstring for which of the 47 legacy columns
were kept, and why the rest were not.
"""

# Generated by Django 5.2.5 on 2026-09-19 08:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_tax_discount_type'),
        ('core', '0005_user_employee'),
        ('devices', '0007_app_release'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('want_approval', models.BooleanField(default=False)),
                ('approval_status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('settings_code', models.CharField(max_length=15, verbose_name='Settings Code')),
                ('header_1', models.CharField(max_length=48, verbose_name='Header 1')),
                ('header_2', models.CharField(max_length=48, verbose_name='Header 2')),
                ('additional_header_1', models.CharField(blank=True, max_length=75, verbose_name='Additional Header 1')),
                ('additional_header_2', models.CharField(blank=True, max_length=75, verbose_name='Additional Header 2')),
                ('footer_1', models.CharField(max_length=75, verbose_name='Footer 1')),
                ('footer_2_arabic', models.CharField(blank=True, max_length=48, verbose_name='Footer 2 (Arabic)')),
                ('paper_feed', models.PositiveSmallIntegerField(default=4, verbose_name='Paper Feed')),
                ('print_type', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='landscape', max_length=16, verbose_name='Print Type')),
                ('print_logo', models.BooleanField(default=True, verbose_name='Print Logo')),
                ('logo', models.ImageField(blank=True, upload_to='device_settings/')),
                ('logo_changed_on', models.DateTimeField(blank=True, null=True)),
                ('receipt_copies', models.PositiveSmallIntegerField(default=1, verbose_name='No of Receipt Copy')),
                ('share_on_whatsapp', models.BooleanField(default=False, verbose_name='Share On WhatsApp')),
                ('order_no_prefix', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]+$', 'Letters and digits only.')], verbose_name='Order No Starting Characters')),
                ('customer_test_minutes', models.PositiveSmallIntegerField(default=5, verbose_name='Customer Test Time Slot (Min)')),
                ('cashier_test_minutes', models.PositiveSmallIntegerField(default=5, verbose_name='Cashier Test Time Slot (Min)')),
                ('round_off_mode', models.CharField(choices=[('nearest', 'Nearest'), ('upward', 'Upward'), ('downward', 'Downward')], default='upward', max_length=16, verbose_name='Round Off Type')),
                ('round_off_step', models.DecimalField(choices=[(Decimal('0.25'), '25 fils'), (Decimal('0.50'), '50 fils'), (Decimal('1.00'), '1 AED')], decimal_places=2, default=Decimal('0.25'), max_digits=4, verbose_name='Round Off Limit')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_settings', to='company.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
            ],
            options={
                'verbose_name_plural': 'device settings',
                'db_table': 'device_settings',
                'ordering': ['branch__name'],
                'indexes': [models.Index(fields=['branch'], name='device_sett_branch__e5ccbd_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('branch',), name='uniq_active_settings_per_branch', violation_error_message='This station already has active settings.'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('settings_code',), name='uniq_active_settings_code', violation_error_message='Settings code already exists.'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('order_no_prefix',), name='uniq_active_order_no_prefix', violation_error_message='Another station already uses this order prefix.'), models.CheckConstraint(condition=models.Q(('paper_feed__lte', 10)), name='device_settings_paper_feed_0_to_10'), models.CheckConstraint(condition=models.Q(('receipt_copies__gte', 1), ('receipt_copies__lte', 10)), name='device_settings_receipt_copies_1_to_10'), models.CheckConstraint(condition=models.Q(('cashier_test_minutes__gt', 0), ('customer_test_minutes__gt', 0)), name='device_settings_test_minutes_positive')],
            },
        ),
    ]
