"""Each device's receipt counter per station, replacing SfaBillContinuity.

Unique per (device, branch, kind), which the legacy never enforced. See the
BillContinuity docstring for how numbering works and what was dropped.
"""

# Generated by Django 5.2.5 on 2026-09-19 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_tax_discount_type'),
        ('core', '0005_user_employee'),
        ('devices', '0008_device_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillContinuity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('kind', models.CharField(choices=[('order', 'Rental order'), ('test_ride', 'Test ride')], max_length=16)),
                ('prefix', models.CharField(max_length=12)),
                ('last_number', models.PositiveBigIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_counters', to='company.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_counters', to='devices.device')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
            ],
            options={
                'verbose_name_plural': 'bill continuity',
                'db_table': 'bill_continuity',
                'ordering': ['device', 'branch', 'kind'],
                'indexes': [models.Index(fields=['branch'], name='bill_contin_branch__0eac91_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'branch', 'kind'), name='uniq_bill_counter_per_device_branch_kind')],
            },
        ),
    ]
