# Generated by Django 5.2.5 on 2026-09-20 03:18

"""The station logo moves into the row, as bytes.

It was an ImageField, which would have needed a media volume of its own to back
up and restore in step with the database. The live logos are 1-bit BMPs 832 dots
wide -- the print head's width -- averaging 25 KB, 2 MB for the whole network,
and the tablet is sent them with its settings so it can print offline. The
legacy stored them in the row as well (base64); bytes are the same picture a
third smaller.

Paper feed's default follows the live rows: 2, not 4.

No data migration: device_settings has no rows yet.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_device_mapping_moments'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesettings',
            name='logo_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Logo File'),
        ),
        migrations.AlterField(
            model_name='devicesettings',
            name='logo',
            field=models.BinaryField(blank=True, editable=True, null=True, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='devicesettings',
            name='paper_feed',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Paper Feed'),
        ),
    ]
