# Generated by Django 5.2.5 on 2026-09-17 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('core', '0003_user_role'),
        ('devices', '0001_initial'),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('channel', models.CharField(choices=[('web', 'Back office web'), ('operator', 'RMS operator app'), ('manager', 'Manager app'), ('employee', 'Employee app')], max_length=16)),
                ('logged_in_at', models.DateTimeField()),
                ('logged_out_at', models.DateTimeField(blank=True, null=True)),
                ('logout_reason', models.CharField(blank=True, choices=[('user_logout', 'Signed out'), ('forced', 'Logged out by an administrator'), ('employee_blocked', 'Employee blocked'), ('device_blocked', 'Device blocked'), ('replaced', 'Replaced by a newer sign-in'), ('expired', 'Expired'), ('token_reuse', 'Refresh token reused')], max_length=24)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_token_hash', models.CharField(blank=True, max_length=128)),
                ('refresh_expires_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('app_version', models.CharField(blank=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='company.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='devices.device')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='core.user')),
            ],
            options={
                'db_table': 'app_session',
                'ordering': ['-logged_in_at'],
                'indexes': [models.Index(fields=['device', 'logged_out_at'], name='app_session_device__817e4e_idx'), models.Index(fields=['logged_in_at'], name='app_session_logged__0887ab_idx'), models.Index(fields=['session_key'], name='app_session_session_835e34_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('logged_out_at__isnull', True)), fields=('user', 'channel'), name='uniq_open_session_per_user_channel')],
            },
        ),
    ]
