# Generated by Django 5.2.5 on 2026-09-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_appsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_flat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='menu_header',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='module',
            name='svg',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='module',
            name='svg2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='page',
            name='svg',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='page',
            name='svg2',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
