# Generated by Django 5.2.5 on 2026-09-18 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_department_company'),
        ('core', '0004_user_scope_user_user_scope_matches_company'),
        ('portal', '0004_seed_company_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='company.company'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', True)), fields=('name',), name='uniq_system_role_name'),
        ),
    ]
