# Generated by Django 5.2.5 on 2026-09-18 03:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_retire_duplicate_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='css_class',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='module',
            name='icon',
            field=models.ImageField(blank=True, upload_to='menu/'),
        ),
        migrations.AddField(
            model_name='page',
            name='css_class',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='page',
            name='icon',
            field=models.ImageField(blank=True, upload_to='menu/'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_recommend',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='actions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('print', 'Print'), ('recommend', 'Recommend'), ('approve', 'Approve')], max_length=16), blank=True, default=list, size=None),
        ),
    ]
