"""Drop app_session.session_key.

It was written at web sign-in and indexed, but nothing ever read it. Force
logout works the other way round: the Django session stores the app_session id,
and core/middleware.py checks on every request that the row is still open -- so
closing the row signs the browser out on its next click, with no need to find
the Django session by its key.
"""

# Generated by Django 5.2.5 on 2026-09-19 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_page_registry'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='appsession',
            name='app_session_session_835e34_idx',
        ),
        migrations.RemoveField(
            model_name='appsession',
            name='session_key',
        ),
    ]
