# Generated by Django 5.2.5 on 2026-09-18 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_department_company'),
        ('core', '0004_user_scope_user_user_scope_matches_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Branch Name'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='short_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Branch Code'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='short_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Company Code'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Country Name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='short_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Country Code'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Department Name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='short_code',
            field=models.CharField(max_length=10, verbose_name='Department Code'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Location Name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='short_code',
            field=models.CharField(max_length=10, verbose_name='Location Code'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=100, verbose_name='State Name'),
        ),
        migrations.AlterField(
            model_name='state',
            name='short_code',
            field=models.CharField(max_length=10, verbose_name='State Code'),
        ),
        migrations.AlterConstraint(
            model_name='branch',
            name='uniq_active_head_office_per_company',
            constraint=models.UniqueConstraint(condition=models.Q(('branch_type', 'head_office'), ('is_active', True)), fields=('company', 'branch_type'), name='uniq_active_head_office_per_company', violation_error_message='This company already has an active head office.'),
        ),
        migrations.AlterConstraint(
            model_name='branchworkingtime',
            name='uniq_branch_weekday_shift',
            constraint=models.UniqueConstraint(fields=('branch', 'week_day', 'shift_number'), name='uniq_branch_weekday_shift', violation_error_message='That shift is already set for this day.'),
        ),
        migrations.AlterConstraint(
            model_name='department',
            name='uniq_department_code_per_company',
            constraint=models.UniqueConstraint(fields=('company', 'short_code'), name='uniq_department_code_per_company', violation_error_message='A department with this code already exists.'),
        ),
        migrations.AlterConstraint(
            model_name='department',
            name='uniq_department_name_per_company',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_department_name_per_company', violation_error_message='A department with this name already exists.'),
        ),
        migrations.AlterConstraint(
            model_name='state',
            name='uniq_state_code_per_country',
            constraint=models.UniqueConstraint(fields=('country', 'short_code'), name='uniq_state_code_per_country', violation_error_message='This country already has a state with that code.'),
        ),
    ]
