# Generated by Django 5.2.5 on 2026-09-18 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_field_labels'),
        ('core', '0004_user_scope_user_user_scope_matches_company'),
        ('crew', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchApprovalAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('authority_type', models.CharField(choices=[('leave_request', 'Leave Request'), ('maintenance', 'Service & Maintenance'), ('rms_app_request', 'RMS App Request')], max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_authority', to='company.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_authority', to='crew.employee')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
            ],
            options={
                'db_table': 'branch_approval_authority',
                'indexes': [models.Index(fields=['branch'], name='branch_appr_branch__5fb588_idx')],
                'constraints': [models.UniqueConstraint(fields=('branch', 'employee', 'authority_type'), name='uniq_branch_employee_authority', violation_error_message='That person already holds this authority at this branch.')],
            },
        ),
    ]
