# Generated by Django 5.2.5 on 2026-09-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_branchapprovalauthority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='short_code',
            field=models.CharField(max_length=20, verbose_name='Location Code'),
        ),
    ]
