# Generated by Django 5.2.5 on 2026-09-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_widen_location_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='discount_type',
            field=models.CharField(choices=[('before_tax', 'Before tax'), ('after_tax', 'After tax')], default='before_tax', max_length=16),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_type',
            field=models.CharField(choices=[('included', 'Included in basic fare'), ('excluded', 'Excluded from basic fare')], default='included', max_length=16),
        ),
    ]
