# Generated by Django 5.2.5 on 2026-09-24 04:18

from django.db import migrations, models

# WeekDay moves from Sunday=0 to Python's Monday=0: new = (old + 6) % 7.
#
# Two steps, not one UPDATE: (branch, week_day, shift_number) is unique and
# PostgreSQL checks a non-deferrable unique constraint row by row, so shifting
# every row in place would collide with a row not yet moved (Monday 1 -> 0
# while Sunday is still 0). Parking the values at +10 first keeps every
# intermediate state unique.
TO_MONDAY_ZERO = [
    "UPDATE branch_working_time SET week_day = week_day + 10",
    "UPDATE branch_working_time SET week_day = (week_day - 10 + 6) % 7",
]
TO_SUNDAY_ZERO = [
    "UPDATE branch_working_time SET week_day = week_day + 10",
    "UPDATE branch_working_time SET week_day = (week_day - 10 + 1) % 7",
]


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_branch_code_per_company'),
    ]

    operations = [
        migrations.RunSQL(TO_MONDAY_ZERO, reverse_sql=TO_SUNDAY_ZERO),
        migrations.AlterField(
            model_name='branchworkingtime',
            name='week_day',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
    ]
