# Generated by Django 5.2.5 on 2026-09-30 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_weekday_monday_zero'),
        ('core', '0005_user_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('want_approval', models.BooleanField(default=False)),
                ('approval_status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, verbose_name='Payment Mode')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_modes', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
            ],
            options={
                'db_table': 'payment_mode',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['company'], name='payment_mod_company_fd8631_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'name'), name='uniq_payment_mode_name_per_company', violation_error_message='A payment mode with this name already exists.')],
            },
        ),
    ]
