# Generated by Django 5.2.5 on 2026-10-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_paymentmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='hotel_commission',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13),
        ),
    ]
