# Generated by Django 5.2.5 on 2026-09-27 22:29

import core.ids
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('level', models.CharField(max_length=10)),
                ('logger', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('exception_type', models.CharField(blank=True, max_length=200)),
                ('traceback', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('api', 'Device API'), ('web', 'Web screen'), ('other', 'Background')], max_length=8)),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=8)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('app', models.CharField(blank=True, max_length=16)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('company_id', models.BigIntegerField(blank=True, null=True)),
                ('installation_id', models.CharField(blank=True, max_length=64)),
                ('device_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'error_log',
                'ordering': ['-created_at'],
                'indexes': [django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='error_log_created_brin'), models.Index(fields=['-created_at'], name='error_log_newest'), models.Index(fields=['request_id'], name='error_log_request')],
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('app', models.CharField(blank=True, max_length=16)),
                ('method', models.CharField(max_length=8)),
                ('path', models.CharField(max_length=255)),
                ('url_name', models.CharField(blank=True, max_length=100)),
                ('status', models.PositiveSmallIntegerField()),
                ('code', models.CharField(blank=True, max_length=64)),
                ('duration_ms', models.PositiveIntegerField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('installation_id', models.CharField(blank=True, max_length=64)),
                ('device_id', models.BigIntegerField(blank=True, null=True)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('company_id', models.BigIntegerField(blank=True, null=True)),
                ('branch_id', models.BigIntegerField(blank=True, null=True)),
                ('request_body', models.TextField(blank=True)),
                ('response_body', models.TextField(blank=True)),
                ('request_truncated', models.BooleanField(default=False)),
                ('response_truncated', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'request_log',
                'ordering': ['-created_at'],
                'indexes': [django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='request_log_created_brin'), models.Index(fields=['-created_at'], name='request_log_newest'), models.Index(fields=['installation_id', '-created_at'], name='request_log_device'), models.Index(condition=models.Q(('status__gte', 400)), fields=['status'], name='request_log_failed')],
            },
        ),
    ]
