"""The fare tables (design/fares and offers/fare-schema.md).

Extensions, created before the tables:
  btree_gist -- lets an exclusion constraint compare plain columns with `=`
                alongside date and minute ranges.
  intarray   -- a GiST operator class for integer arrays, so a constraint can
                refuse two selected-days rules that share a weekday. Note: it
                also takes over &&, @> and <@ for every integer[] column in the
                database. None exists today (the other arrays are varchar).
Both are "trusted" extensions (PostgreSQL 13+): any role with CREATE on the
database may install them. CreateExtension skips one that already exists.

Two composite foreign keys, added in SQL because Django cannot express them:

  fare_branch (fare_id, level, vehicle_type_id, package_minutes, valid_from,
  valid_to, is_active) -> fare (...), ON UPDATE CASCADE: a branch link's
  copies are held for fare_branch_no_overlap, and Postgres keeps them equal
  to the fare's -- change a fare's dates and its links follow. Same idea as
  devices 0007/0012.

  fare_rule (season_id, fare_id) -> fare_season (id, fare_id): a rule's
  season always belongs to the rule's own fare, which the per-list exclusion
  constraints rely on. A fare-level rule has no season; MATCH SIMPLE skips it.

Neither is deferrable: cascades are immediate anyway, and a wrong copy should
fail at once. Django does not know they exist -- a later AlterField on any of
these columns has to drop and re-add them.
"""

# Generated by Django 5.2.5 on 2026-09-24 05:19

import apps.fare.db
import django.contrib.postgres.constraints
import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.indexes
import django.db.models.constraints
import django.db.models.deletion
from django.contrib.postgres.operations import BtreeGistExtension, CreateExtension
from django.db import migrations, models

COMPOSITE_FKS = """
ALTER TABLE fare_branch
    ADD CONSTRAINT fare_branch_fare_copy_fk
    FOREIGN KEY (fare_id, level, vehicle_type_id, package_minutes, valid_from, valid_to, is_active)
    REFERENCES fare (id, level, vehicle_type_id, package_minutes, valid_from, valid_to, is_active)
    ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE fare_rule
    ADD CONSTRAINT fare_rule_season_same_fare_fk
    FOREIGN KEY (season_id, fare_id)
    REFERENCES fare_season (id, fare_id)
    ON DELETE CASCADE;
"""

DROP_COMPOSITE_FKS = """
ALTER TABLE fare_rule DROP CONSTRAINT IF EXISTS fare_rule_season_same_fare_fk;
ALTER TABLE fare_branch DROP CONSTRAINT IF EXISTS fare_branch_fare_copy_fk;
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0008_weekday_monday_zero'),
        ('core', '0005_user_employee'),
        ('fleet', '0007_vehicletype_other_tax_vehicletype_tax_percentage'),
    ]

    operations = [
        BtreeGistExtension(),
        CreateExtension("intarray"),
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('want_approval', models.BooleanField(default=False)),
                ('approval_status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Basic Fare')),
                ('grace_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='Grace Period')),
                ('concurrent_interval_minutes', models.PositiveSmallIntegerField(verbose_name='Concurrent Interval')),
                ('concurrent_fare', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Concurrent Fare')),
                ('concurrent_grace_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='Concurrent Grace')),
                ('level', models.CharField(choices=[('company', 'Company'), ('branch', 'Branch')], max_length=10, verbose_name='Fare Level')),
                ('valid_from', models.DateField(verbose_name='Valid From')),
                ('valid_to', models.DateField(verbose_name='Valid To')),
                ('package_minutes', models.PositiveSmallIntegerField(verbose_name='Package Time')),
                ('lock_version', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fares', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fares', to='fleet.vehicletype')),
            ],
            options={
                'db_table': 'fare',
                'ordering': ['-valid_from', 'vehicle_type__vehicle_type_name'],
            },
        ),
        migrations.CreateModel(
            name='FareBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('company', 'Company'), ('branch', 'Branch')], default='branch', max_length=10)),
                ('package_minutes', models.PositiveSmallIntegerField()),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('is_active', models.BooleanField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fare_links', to='company.branch')),
                ('fare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_links', to='fare.fare')),
                ('vehicle_type', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fleet.vehicletype')),
            ],
            options={
                'verbose_name': 'branch fare',
                'verbose_name_plural': 'branch fares',
                'db_table': 'fare_branch',
            },
        ),
        migrations.AddField(
            model_name='fare',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='fares', through='fare.FareBranch', to='company.branch'),
        ),
        migrations.CreateModel(
            name='FareSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Basic Fare')),
                ('grace_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='Grace Period')),
                ('concurrent_interval_minutes', models.PositiveSmallIntegerField(verbose_name='Concurrent Interval')),
                ('concurrent_fare', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Concurrent Fare')),
                ('concurrent_grace_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='Concurrent Grace')),
                ('name', models.CharField(max_length=100, verbose_name='Season Name')),
                ('start_date', models.DateField(verbose_name='From Date')),
                ('end_date', models.DateField(verbose_name='To Date')),
                ('fare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='fare.fare')),
            ],
            options={
                'db_table': 'fare_season',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='FareRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Basic Fare')),
                ('grace_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='Grace Period')),
                ('concurrent_interval_minutes', models.PositiveSmallIntegerField(verbose_name='Concurrent Interval')),
                ('concurrent_fare', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Concurrent Fare')),
                ('concurrent_grace_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='Concurrent Grace')),
                ('kind', models.CharField(choices=[('every_day', 'Every day'), ('selected_days', 'Selected days'), ('single_date', 'Single date')], max_length=16)),
                ('weekdays', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]), blank=True, default=list, size=None)),
                ('on_date', models.DateField(blank=True, null=True)),
                ('start_minute', models.PositiveSmallIntegerField()),
                ('end_minute', models.PositiveSmallIntegerField()),
                ('fare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='fare.fare')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='fare.fareseason')),
            ],
            options={
                'db_table': 'fare_rule',
                'ordering': ['kind', 'on_date', 'start_minute'],
            },
        ),
        migrations.AddConstraint(
            model_name='farebranch',
            constraint=models.UniqueConstraint(fields=('fare', 'branch'), name='fare_branch_once'),
        ),
        migrations.AddConstraint(
            model_name='farebranch',
            constraint=models.CheckConstraint(condition=models.Q(('level', 'branch')), name='fare_branch_branch_level_only'),
        ),
        migrations.AddConstraint(
            model_name='farebranch',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('is_active', True)), deferrable=django.db.models.constraints.Deferrable['IMMEDIATE'], expressions=[('branch', '='), ('vehicle_type', '='), ('package_minutes', '='), (apps.fare.db.DateRangeFunc('valid_from', 'valid_to', django.contrib.postgres.fields.ranges.RangeBoundary(inclusive_lower=True, inclusive_upper=True)), '&&')], name='fare_branch_no_overlap', violation_error_message='Another active fare already covers this branch on these dates.'),
        ),
        migrations.AddConstraint(
            model_name='fare',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__gte', models.F('valid_from'))), name='fare_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='fare',
            constraint=models.CheckConstraint(condition=models.Q(('package_minutes__gt', 0)), name='fare_package_positive'),
        ),
        migrations.AddConstraint(
            model_name='fare',
            constraint=models.CheckConstraint(condition=models.Q(('base_fare__gte', 0), ('concurrent_fare__gte', 0)), name='fare_money_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='fare',
            constraint=models.CheckConstraint(condition=models.Q(('concurrent_interval_minutes__gt', 0)), name='fare_interval_positive'),
        ),
        migrations.AddConstraint(
            model_name='fare',
            constraint=models.UniqueConstraint(fields=('id', 'level', 'vehicle_type', 'package_minutes', 'valid_from', 'valid_to', 'is_active'), name='fare_copy_key'),
        ),
        migrations.AddConstraint(
            model_name='fare',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('is_active', True), ('level', 'company')), deferrable=django.db.models.constraints.Deferrable['IMMEDIATE'], expressions=[('company', '='), ('vehicle_type', '='), ('package_minutes', '='), (apps.fare.db.DateRangeFunc('valid_from', 'valid_to', django.contrib.postgres.fields.ranges.RangeBoundary(inclusive_lower=True, inclusive_upper=True)), '&&')], name='fare_company_no_overlap', violation_error_message='Another active company fare already covers these dates.'),
        ),
        migrations.AddConstraint(
            model_name='fareseason',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='fare_season_dates'),
        ),
        migrations.AddConstraint(
            model_name='fareseason',
            constraint=models.CheckConstraint(condition=models.Q(('base_fare__gte', 0), ('concurrent_fare__gte', 0)), name='fare_season_money_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='fareseason',
            constraint=models.CheckConstraint(condition=models.Q(('concurrent_interval_minutes__gt', 0)), name='fare_season_interval_positive'),
        ),
        migrations.AddConstraint(
            model_name='fareseason',
            constraint=models.UniqueConstraint(fields=('id', 'fare'), name='fare_season_id_fare'),
        ),
        migrations.AddConstraint(
            model_name='fareseason',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(deferrable=django.db.models.constraints.Deferrable['IMMEDIATE'], expressions=[('fare', '='), (apps.fare.db.DateRangeFunc('start_date', 'end_date', django.contrib.postgres.fields.ranges.RangeBoundary(inclusive_lower=True, inclusive_upper=True)), '&&')], name='fare_season_no_overlap', violation_error_message='A date can belong to one season only.'),
        ),
        migrations.AddConstraint(
            model_name='farerule',
            constraint=models.CheckConstraint(condition=models.Q(('base_fare__gte', 0), ('concurrent_fare__gte', 0)), name='fare_rule_money_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='farerule',
            constraint=models.CheckConstraint(condition=models.Q(('concurrent_interval_minutes__gt', 0)), name='fare_rule_interval_positive'),
        ),
        migrations.AddConstraint(
            model_name='farerule',
            constraint=models.CheckConstraint(condition=models.Q(('end_minute__gt', models.F('start_minute')), ('end_minute__lte', 1440)), name='fare_rule_window'),
        ),
        migrations.AddConstraint(
            model_name='farerule',
            constraint=models.CheckConstraint(condition=models.Q(('weekdays__contained_by', [0, 1, 2, 3, 4, 5, 6])), name='fare_rule_weekday_values'),
        ),
        migrations.AddConstraint(
            model_name='farerule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'every_day'), ('on_date__isnull', True), ('weekdays__len', 0)), models.Q(('kind', 'selected_days'), ('on_date__isnull', True), ('weekdays__len__gt', 0)), models.Q(('kind', 'single_date'), ('on_date__isnull', False), ('season__isnull', True), ('weekdays__len', 0)), _connector='OR'), name='fare_rule_kind_fields'),
        ),
        migrations.AddConstraint(
            model_name='farerule',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('kind', 'every_day'), ('season__isnull', True)), deferrable=django.db.models.constraints.Deferrable['IMMEDIATE'], expressions=[('fare', '='), (apps.fare.db.IntRangeFunc('start_minute', 'end_minute'), '&&')], name='fare_rule_every_day_fare', violation_error_message='Two prices of the same kind cannot cover the same time.'),
        ),
        migrations.AddConstraint(
            model_name='farerule',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('kind', 'every_day'), ('season__isnull', False)), deferrable=django.db.models.constraints.Deferrable['IMMEDIATE'], expressions=[('season', '='), (apps.fare.db.IntRangeFunc('start_minute', 'end_minute'), '&&')], name='fare_rule_every_day_season', violation_error_message='Two prices of the same kind cannot cover the same time.'),
        ),
        migrations.AddConstraint(
            model_name='farerule',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('kind', 'selected_days'), ('season__isnull', True)), deferrable=django.db.models.constraints.Deferrable['IMMEDIATE'], expressions=[('fare', '='), (django.contrib.postgres.indexes.OpClass('weekdays', name='gist__int_ops'), '&&'), (apps.fare.db.IntRangeFunc('start_minute', 'end_minute'), '&&')], name='fare_rule_days_fare', violation_error_message='Two prices of the same kind cannot cover the same time.'),
        ),
        migrations.AddConstraint(
            model_name='farerule',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('kind', 'selected_days'), ('season__isnull', False)), deferrable=django.db.models.constraints.Deferrable['IMMEDIATE'], expressions=[('season', '='), (django.contrib.postgres.indexes.OpClass('weekdays', name='gist__int_ops'), '&&'), (apps.fare.db.IntRangeFunc('start_minute', 'end_minute'), '&&')], name='fare_rule_days_season', violation_error_message='Two prices of the same kind cannot cover the same time.'),
        ),
        migrations.AddConstraint(
            model_name='farerule',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('kind', 'single_date')), deferrable=django.db.models.constraints.Deferrable['IMMEDIATE'], expressions=[('fare', '='), ('on_date', '='), (apps.fare.db.IntRangeFunc('start_minute', 'end_minute'), '&&')], name='fare_rule_single_date', violation_error_message='Two prices of the same kind cannot cover the same time.'),
        ),
        migrations.RunSQL(COMPOSITE_FKS, DROP_COMPOSITE_FKS),
    ]
