# Generated by Django 5.2.5 on 2026-09-28 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_weekday_monday_zero'),
        ('core', '0005_user_employee'),
        ('fare', '0002_nested_windows'),
        ('fleet', '0012_vehicle_identifier_vb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('want_approval', models.BooleanField(default=False)),
                ('approval_status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('offer_code', models.CharField(max_length=30, verbose_name='Promotion Code')),
                ('offer_name', models.CharField(max_length=100, verbose_name='Promotion Name')),
                ('level', models.CharField(choices=[('company', 'Company Wise'), ('branch', 'Branch Wise'), ('location', 'Location Wise')], default='company', max_length=10, verbose_name='Promotion Level')),
                ('valid_from', models.DateField(verbose_name='Valid From')),
                ('valid_to', models.DateField(verbose_name='Valid To')),
                ('promotion_for', models.CharField(choices=[('quantity', 'Quantity'), ('amount', 'Amount')], max_length=10, verbose_name='Promotion For')),
                ('inventory_type', models.CharField(choices=[('vehicle_type', 'Vehicle Type')], default='vehicle_type', max_length=20, verbose_name='Inventory Type')),
                ('lower_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Lower Promotion Value')),
                ('upper_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Upper Promotion Value')),
                ('promotion_type', models.CharField(choices=[('quantity', 'Quantity'), ('amount', 'Amount'), ('percentage', 'Percentage'), ('each', 'Each'), ('offer_price', 'Offer Price')], max_length=12, verbose_name='Promotion Type')),
                ('time_slab_applicable', models.BooleanField(default=False, verbose_name='Time Slab Applicable')),
                ('free_item_selectable', models.BooleanField(default=False, verbose_name='Free Item Selectable')),
                ('free_item_selectable_note', models.CharField(blank=True, max_length=255)),
                ('free_or_offer_price', models.CharField(choices=[('free', 'Free'), ('offer_price', 'Offer Price')], default='free', max_length=12, verbose_name='Free / Offer Price')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='company.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='company.location')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
            ],
            options={
                'db_table': 'offer',
                'ordering': ['-valid_from', 'offer_name'],
            },
        ),
        migrations.CreateModel(
            name='OfferFreeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_minutes', models.PositiveSmallIntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_items', to='fare.offer')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_free_items', to='fleet.vehicletype')),
            ],
            options={
                'db_table': 'offer_free_item',
            },
        ),
        migrations.CreateModel(
            name='OfferFreeItemTimeSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mode', models.CharField(choices=[('all_dates', 'All Dates'), ('specific_date', 'Specific Date')], default='all_dates', max_length=15)),
                ('specific_date', models.DateField(blank=True, null=True)),
                ('day', models.CharField(choices=[('all_days', 'All Days'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='all_days', max_length=10)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('package_minutes', models.PositiveSmallIntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slabs', to='fare.offer')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_time_slabs', to='fleet.vehicletype')),
            ],
            options={
                'db_table': 'offer_free_item_time_slab',
            },
        ),
        migrations.CreateModel(
            name='OfferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_minutes', models.PositiveSmallIntegerField()),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fare.offer')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_items', to='fleet.vehicletype')),
            ],
            options={
                'db_table': 'offer_item',
            },
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(fields=('company', 'offer_code'), name='uniq_offer_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__gte', models.F('valid_from'))), name='offer_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(condition=models.Q(('upper_value__gte', models.F('lower_value'))), name='offer_value_band'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('branch__isnull', True), ('level', 'company'), ('location__isnull', True)), models.Q(('branch__isnull', False), ('level', 'branch'), ('location__isnull', True)), models.Q(('branch__isnull', True), ('level', 'location'), ('location__isnull', False)), _connector='OR'), name='offer_scope_matches_level'),
        ),
        migrations.AddConstraint(
            model_name='offerfreeitem',
            constraint=models.CheckConstraint(condition=models.Q(('package_minutes__gt', 0), ('package_minutes__lte', 1440)), name='offer_free_item_package_range'),
        ),
        migrations.AddConstraint(
            model_name='offerfreeitem',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='offer_free_item_value_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='offerfreeitemtimeslab',
            constraint=models.CheckConstraint(condition=models.Q(('to_time__gt', models.F('from_time'))), name='offer_slab_time_order'),
        ),
        migrations.AddConstraint(
            model_name='offerfreeitemtimeslab',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('date_mode', 'all_dates'), ('specific_date__isnull', True)), models.Q(('date_mode', 'specific_date'), ('specific_date__isnull', False)), _connector='OR'), name='offer_slab_date_matches_mode'),
        ),
        migrations.AddConstraint(
            model_name='offerfreeitemtimeslab',
            constraint=models.CheckConstraint(condition=models.Q(('package_minutes__gt', 0), ('package_minutes__lte', 1440)), name='offer_slab_package_range'),
        ),
        migrations.AddConstraint(
            model_name='offerfreeitemtimeslab',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='offer_slab_value_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='offeritem',
            constraint=models.CheckConstraint(condition=models.Q(('package_minutes__gt', 0), ('package_minutes__lte', 1440)), name='offer_item_package_range'),
        ),
        migrations.AddConstraint(
            model_name='offeritem',
            constraint=models.CheckConstraint(condition=models.Q(('value__isnull', True), ('value__gte', 0), _connector='OR'), name='offer_item_value_not_negative'),
        ),
    ]
