# Generated by Django 5.2.5 on 2026-10-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fare', '0004_offer_to_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fare',
            name='base_fare',
            field=models.DecimalField(decimal_places=3, max_digits=13, verbose_name='Basic Fare'),
        ),
        migrations.AlterField(
            model_name='fare',
            name='concurrent_fare',
            field=models.DecimalField(decimal_places=3, max_digits=13, verbose_name='Concurrent Fare'),
        ),
        migrations.AlterField(
            model_name='farerule',
            name='base_fare',
            field=models.DecimalField(decimal_places=3, max_digits=13, verbose_name='Basic Fare'),
        ),
        migrations.AlterField(
            model_name='farerule',
            name='concurrent_fare',
            field=models.DecimalField(decimal_places=3, max_digits=13, verbose_name='Concurrent Fare'),
        ),
        migrations.AlterField(
            model_name='fareseason',
            name='base_fare',
            field=models.DecimalField(decimal_places=3, max_digits=13, verbose_name='Basic Fare'),
        ),
        migrations.AlterField(
            model_name='fareseason',
            name='concurrent_fare',
            field=models.DecimalField(decimal_places=3, max_digits=13, verbose_name='Concurrent Fare'),
        ),
        migrations.AlterField(
            model_name='package',
            name='lower_value',
            field=models.DecimalField(decimal_places=3, max_digits=13, verbose_name='Lower Promotion Value'),
        ),
        migrations.AlterField(
            model_name='package',
            name='upper_value',
            field=models.DecimalField(decimal_places=3, max_digits=13, verbose_name='Upper Promotion Value'),
        ),
        migrations.AlterField(
            model_name='packagefreeitem',
            name='value',
            field=models.DecimalField(decimal_places=3, max_digits=13),
        ),
        migrations.AlterField(
            model_name='packagefreeitemtimeslab',
            name='value',
            field=models.DecimalField(decimal_places=3, max_digits=13),
        ),
        migrations.AlterField(
            model_name='packageitem',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
    ]
