# Generated by Django 5.2.5 on 2026-09-28 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0008_weekday_monday_zero'),
        ('core', '0005_user_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('want_approval', models.BooleanField(default=False)),
                ('approval_status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('customer_code', models.CharField(max_length=20, verbose_name='Customer Code')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Last Name')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('id_type', models.CharField(blank=True, choices=[('emirates_id', 'Emirates ID'), ('passport', 'Passport'), ('driving_license', 'Driving License'), ('others', 'Others')], max_length=20, verbose_name='ID Type')),
                ('id_no', models.CharField(blank=True, max_length=100, verbose_name='Document No')),
                ('id_document', models.FileField(blank=True, upload_to='customers/', verbose_name='Document Upload')),
                ('mobile_country_code', models.CharField(max_length=10, verbose_name='Country Code')),
                ('mobile_no', models.CharField(max_length=20, verbose_name='Phone No')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('block_reason', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
            ],
            options={
                'db_table': 'customer',
                'ordering': ['customer_code'],
                'indexes': [models.Index(fields=['company'], name='customer_company_70fe37_idx'), models.Index(fields=['mobile_no'], name='customer_mobile__776eca_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'customer_code'), name='uniq_customer_code_per_company', violation_error_message='A customer with this code already exists.'), models.UniqueConstraint(fields=('mobile_no',), name='uniq_customer_mobile_no', violation_error_message='A customer with this phone number already exists.')],
            },
        ),
    ]
