# Generated by Django 5.2.5 on 2026-09-30 01:53

import re

from django.db import migrations, models


def fill_mobile_full(apps, schema_editor):
    """Existing customers get their full number before it becomes unique --
    same rule as apps/rental/models.py::full_number (a migration must not
    import app code that can change later)."""
    Customer = apps.get_model("rental", "Customer")
    for customer in Customer.objects.only("pk", "mobile_country_code", "mobile_no"):
        customer.mobile_full = (re.sub(r"\D", "", customer.mobile_country_code or "")
                                + re.sub(r"\D", "", customer.mobile_no or ""))
        customer.save(update_fields=["mobile_full"])


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_weekday_monday_zero'),
        ('core', '0005_user_employee'),
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='uniq_customer_mobile_no',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customer_mobile__776eca_idx',
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile_full',
            field=models.CharField(default='', editable=False, max_length=30, verbose_name='Full Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='sync_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        # The unique rule is added in 0003, in its own transaction: Postgres
        # refuses ALTER TABLE on a table with row updates still pending their
        # deferred foreign-key checks.
        migrations.RunPython(fill_mobile_full, migrations.RunPython.noop),
    ]
