# Generated by Django 5.2.5 on 2026-09-30 10:00

import core.ids
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_paymentmode'),
        ('core', '0005_user_employee'),
        ('devices', '0012_device_settings_company'),
        ('fare', '0003_offer_offerfreeitem_offerfreeitemtimeslab_offeritem_and_more'),
        ('fleet', '0013_vehicle_type_is_direct_rent'),
        ('rental', '0002_order_orderitem_order_order_branch__00731f_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('advance', 'Advance'), ('rental', 'Rental'), ('refund', 'Refund')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_no', models.CharField(blank=True, max_length=50)),
                ('reference_date', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField()),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'payment',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.RenameField(
            model_name='order',
            old_name='deposit_amount',
            new_name='advance_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='expected_end_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 30, 10, 0, 34, 994942, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fare.offer'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('expected_end_time__gte', models.F('start_time'))), name='order_item_expected_end_after_start'),
        ),
        migrations.AddField(
            model_name='payment',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='payment',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='devices.device'),
        ),
        migrations.AddField(
            model_name='payment',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='company.paymentmode'),
        ),
        migrations.AddField(
            model_name='payment',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='rental.order'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order'], name='payment_order_i_f08ba7_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
    ]
