# Generated by Django 5.2.5 on 2026-09-30 10:12

import core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_payment_rename_deposit_amount_order_advance_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
