# Generated by Django 5.2.5 on 2026-10-01 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_employee'),
        ('devices', '0012_device_settings_company'),
        ('rental', '0006_payment_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('book', 'Booked'), ('add', 'Vehicle added'), ('replace', 'Vehicle replaced'), ('remove', 'Vehicle removed'), ('return', 'Vehicle returned'), ('payment', 'Payment'), ('settle', 'Settled'), ('cancel_request', 'Cancel requested'), ('cancel_approved', 'Cancel approved'), ('cancel_rejected', 'Cancel rejected')], max_length=20)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('request_hash', models.CharField(max_length=64)),
                ('response', models.JSONField(default=dict)),
                ('happened_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_events', to='devices.device')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rental.orderitem')),
                ('new_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rental.orderitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='rental.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
            ],
            options={
                'db_table': 'order_event',
                'ordering': ['happened_at'],
                'indexes': [models.Index(fields=['order', 'happened_at'], name='order_event_order_i_23fc21_idx')],
            },
        ),
    ]
