# Generated by Django 5.2.5 on 2026-10-02 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_paymentmode'),
        ('core', '0005_user_employee'),
        ('devices', '0012_device_settings_company'),
        ('rental', '0008_bill_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='run_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(max_length=30)),
                ('issued_at', models.DateTimeField()),
                ('company_name', models.CharField(max_length=200)),
                ('company_trn', models.CharField(blank=True, max_length=100)),
                ('branch_name', models.CharField(max_length=200)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_mobile', models.CharField(blank=True, max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rounding_adjustment', models.DecimalField(decimal_places=2, max_digits=6)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payments', models.JSONField(default=list)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='company.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='devices.device')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='rental.order')),
            ],
            options={
                'db_table': 'invoice',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('vehicle_identifier', models.CharField(max_length=20)),
                ('vehicle_name', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(max_length=200)),
                ('package_minutes', models.PositiveSmallIntegerField()),
                ('run_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=12)),
                ('overtime_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rental.invoice')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rental.orderitem')),
            ],
            options={
                'db_table': 'invoice_item',
                'ordering': ['start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['branch', 'issued_at'], name='invoice_branch__b01545_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('company', 'invoice_no'), name='uniq_invoice_no_per_company'),
        ),
    ]
