# Generated by Django 5.2.5 on 2026-10-06 11:12

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_paymentmode'),
        ('core', '0005_user_employee'),
        ('devices', '0012_device_settings_company'),
        ('rental', '0010_item_removed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevent',
            name='action',
            field=models.CharField(choices=[('book', 'Booked'), ('add', 'Vehicle added'), ('replace', 'Vehicle replaced'), ('remove', 'Vehicle removed'), ('return', 'Vehicle returned'), ('payment', 'Payment'), ('settle', 'Settled'), ('cancel_request', 'Cancel requested'), ('cancel_approved', 'Cancel approved'), ('cancel_rejected', 'Cancel rejected'), ('credit_note_request', 'Credit note requested'), ('credit_note_cancel', 'Credit note request cancelled')], max_length=20),
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('device', 'Device request'), ('web', 'Issued on the web')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_remark', models.TextField(blank=True)),
                ('credit_note_no', models.CharField(blank=True, max_length=40)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tax_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('taxable_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='company.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='devices.device')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='rental.invoice')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='rental.order')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
            ],
            options={
                'db_table': 'credit_note',
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['branch', 'status'], name='credit_note_branch__c0f72f_idx'), models.Index(fields=['status', 'created_on'], name='credit_note_status_3cd24b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'approved'))), fields=('order',), name='uniq_live_credit_note_per_order'), models.UniqueConstraint(condition=models.Q(('credit_note_no', ''), _negated=True), fields=('company', 'credit_note_no'), name='uniq_credit_note_no_per_company'), models.CheckConstraint(condition=models.Q(models.Q(('decided_at__isnull', False), ('net_amount', django.db.models.expressions.CombinedExpression(models.F('taxable_amount'), '+', models.F('tax_amount'))), ('net_amount__gt', 0), ('status', 'approved'), ('tax_amount__isnull', False), ('tax_percentage__isnull', False), ('taxable_amount__isnull', False), models.Q(('credit_note_no', ''), _negated=True)), models.Q(models.Q(('status', 'approved'), _negated=True), ('credit_note_no', ''), ('net_amount__isnull', True), ('tax_amount__isnull', True), ('taxable_amount__isnull', True)), _connector='OR'), name='credit_note_amounts_only_when_approved'), models.CheckConstraint(condition=models.Q(models.Q(('decided_at__isnull', True), ('decided_by__isnull', True), ('status', 'pending')), models.Q(models.Q(('status', 'pending'), _negated=True), ('decided_at__isnull', False)), _connector='OR'), name='credit_note_decided_unless_pending'), models.CheckConstraint(condition=models.Q(models.Q(('source', 'web'), ('status', 'approved')), ('source', 'device'), _connector='OR'), name='credit_note_web_is_issued')],
            },
        ),
    ]
