"""Money to the 3rd decimal (7 Oct 2026): (12,2) -> (13,3).

Values keep their value (45.50 -> 45.500). paid_amount and balance_due are
recomputed by the database when they are added back."""

# Generated by Django 5.2.5 on 2026-10-07 12:04

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0011_credit_note'),
    ]

    operations = [
        # Postgres will not change the type of a column a generated column
        # reads, so the two generated columns go first and come back last.
        migrations.RemoveField(model_name='order', name='balance_due'),
        migrations.RemoveField(model_name='order', name='paid_amount'),
        migrations.AlterField(
            model_name='creditnote',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='taxable_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=3, max_digits=13),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='net_amount',
            field=models.DecimalField(decimal_places=3, max_digits=13),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='rounding_adjustment',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=3, max_digits=13),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=3, max_digits=13),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='base_fare',
            field=models.DecimalField(decimal_places=3, max_digits=13),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='overtime_amount',
            field=models.DecimalField(decimal_places=3, max_digits=13),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, max_digits=13),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount_received',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount_refunded',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='hotel_commission',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='order',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='rounding_adjustment',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='base_fare',
            field=models.DecimalField(decimal_places=3, max_digits=13),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='overtime_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=13),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_amount',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('amount_received'), '-', models.F('amount_refunded')), output_field=models.DecimalField(decimal_places=3, max_digits=13)),
        ),
        migrations.AddField(
            model_name='order',
            name='balance_due',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('net_amount'), '-', django.db.models.expressions.CombinedExpression(models.F('amount_received'), '-', models.F('amount_refunded'))), output_field=models.DecimalField(decimal_places=3, max_digits=13)),
        ),
    ]
