# Generated by Django 5.2.5 on 2026-10-08 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_money_three_decimals'),
        ('core', '0005_user_employee'),
        ('devices', '0012_device_settings_company'),
        ('rental', '0012_money_three_decimals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevent',
            name='action',
            field=models.CharField(choices=[('book', 'Booked'), ('add', 'Vehicle added'), ('replace', 'Vehicle replaced'), ('remove', 'Vehicle removed'), ('return', 'Vehicle returned'), ('payment', 'Payment'), ('settle', 'Settled'), ('cancel_request', 'Cancel requested'), ('cancel_approved', 'Cancel approved'), ('cancel_rejected', 'Cancel rejected'), ('credit_note_request', 'Credit note requested'), ('credit_note_cancel', 'Credit note request cancelled'), ('request', 'Request sent'), ('request_withdraw', 'Request withdrawn')], max_length=20),
        ),
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('discount', 'Discount')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('closed', 'Closed'), ('revoked', 'Revoked')], max_length=10)),
                ('requested_at', models.DateTimeField()),
                ('reason', models.TextField(blank=True)),
                ('discount_type', models.CharField(blank=True, choices=[('percent', 'Percentage'), ('amount', 'Amount (AED)')], max_length=10)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('decided_channel', models.CharField(blank=True, choices=[('web', 'Web'), ('manager', 'Manager app')], max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('revoked_channel', models.CharField(blank=True, choices=[('web', 'Web'), ('manager', 'Manager app')], max_length=10)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_note', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_requests', to='company.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_requests', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='devices.device')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='rental.order')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
            ],
            options={
                'db_table': 'order_request',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', 'requested_at'], name='order_reque_status_f9cc91_idx'), models.Index(fields=['branch', 'status'], name='order_reque_branch__338a32_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'approved'))), fields=('order', 'kind'), name='uniq_live_request_per_order_kind'), models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', True), ('decided_at__isnull', True), ('decided_by__isnull', True), ('revoked_at__isnull', True), ('status', 'pending')), models.Q(('closed_at__isnull', True), ('decided_at__isnull', False), ('revoked_at__isnull', True), ('status', 'approved')), models.Q(('closed_at__isnull', True), ('decided_at__isnull', False), ('revoked_at__isnull', True), ('status', 'rejected')), models.Q(('closed_at__isnull', True), ('decided_at__isnull', False), ('revoked_at__isnull', False), ('status', 'revoked')), models.Q(('closed_at__isnull', False), ('decided_at__isnull', True), ('status__in', ['withdrawn', 'closed'])), _connector='OR'), name='order_request_status_fields'), models.CheckConstraint(condition=models.Q(models.Q(('discount_type__in', ['percent', 'amount']), ('discount_value__gt', 0), ('kind', 'discount'), ('status__in', ['approved', 'revoked'])), models.Q(models.Q(('kind', 'discount'), ('status__in', ['approved', 'revoked']), _negated=True), ('discount_type', ''), ('discount_value__isnull', True)), _connector='OR'), name='order_request_discount_rule'), models.CheckConstraint(condition=models.Q(models.Q(('discount_type', 'percent'), _negated=True), ('discount_value__lte', 100), _connector='OR'), name='order_request_percent_at_most_100'), models.CheckConstraint(condition=models.Q(models.Q(('applied_amount__isnull', True), ('applied_at__isnull', True)), models.Q(('applied_amount__isnull', False), ('applied_at__isnull', False), ('status', 'approved')), _connector='OR'), name='order_request_applied_only_when_approved')],
            },
        ),
    ]
