# Generated by Django 5.2.5 on 2026-10-08 08:37

from django.db import migrations, models


def card_until_now(apps, schema_editor):
    """Every discount on an invoice so far was a card discount -- the only kind
    the settle took before manager discounts and complimentary rides."""
    Invoice = apps.get_model("rental", "Invoice")
    Invoice.objects.filter(discount_amount__gt=0).update(discount_source="card")


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_money_three_decimals'),
        ('core', '0005_user_employee'),
        ('devices', '0012_device_settings_company'),
        ('rental', '0013_order_request'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderrequest',
            name='order_request_status_fields',
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_source',
            field=models.CharField(blank=True, choices=[('card', 'Card discount'), ('manager', 'Discount'), ('complimentary', 'Complimentary')], max_length=15),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='action',
            field=models.CharField(choices=[('book', 'Booked'), ('add', 'Vehicle added'), ('replace', 'Vehicle replaced'), ('remove', 'Vehicle removed'), ('return', 'Vehicle returned'), ('payment', 'Payment'), ('settle', 'Settled'), ('cancel_request', 'Cancel requested'), ('cancel_approved', 'Cancel approved'), ('cancel_rejected', 'Cancel rejected'), ('credit_note_request', 'Credit note requested'), ('credit_note_cancel', 'Credit note request cancelled'), ('request', 'Request sent'), ('request_withdraw', 'Request withdrawn'), ('request_used', 'Reprint printed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='kind',
            field=models.CharField(choices=[('discount', 'Discount'), ('complimentary', 'Complimentary'), ('reprint', 'Reprint')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('closed', 'Closed'), ('revoked', 'Revoked'), ('used', 'Used')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='orderrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', True), ('decided_at__isnull', True), ('decided_by__isnull', True), ('revoked_at__isnull', True), ('status', 'pending'), ('used_at__isnull', True)), models.Q(('closed_at__isnull', True), ('decided_at__isnull', False), ('revoked_at__isnull', True), ('status', 'approved'), ('used_at__isnull', True)), models.Q(('closed_at__isnull', True), ('decided_at__isnull', False), ('revoked_at__isnull', True), ('status', 'rejected'), ('used_at__isnull', True)), models.Q(('closed_at__isnull', True), ('decided_at__isnull', False), ('revoked_at__isnull', False), ('status', 'revoked'), ('used_at__isnull', True)), models.Q(('closed_at__isnull', False), ('decided_at__isnull', True), ('status__in', ['withdrawn', 'closed']), ('used_at__isnull', True)), models.Q(('closed_at__isnull', True), ('decided_at__isnull', False), ('kind', 'reprint'), ('revoked_at__isnull', True), ('status', 'used'), ('used_at__isnull', False)), _connector='OR'), name='order_request_status_fields'),
        ),
        migrations.RunPython(card_until_now, migrations.RunPython.noop),
    ]
