# Generated by Django 5.2.5 on 2026-10-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_money_three_decimals'),
        ('core', '0005_user_employee'),
        ('devices', '0012_device_settings_company'),
        ('discount', '0003_money_three_decimals'),
        ('rental', '0014_complimentary_reprint'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['branch', 'booked_at'], name='order_branch__1a0a3e_idx'),
        ),
    ]
