# Generated by Django 5.2.5 on 2026-09-22 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0007_branch_code_per_company'),
        ('core', '0005_user_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('want_approval', models.BooleanField(default=False)),
                ('approval_status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('brand_code', models.CharField(max_length=20, verbose_name='Brand Code')),
                ('brand_name', models.CharField(max_length=100, verbose_name='Brand Name')),
                ('description', models.TextField(blank=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('website_link', models.URLField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
            ],
            options={
                'db_table': 'brand',
                'ordering': ['brand_name'],
                'indexes': [models.Index(fields=['company'], name='brand_company_c099d5_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'brand_code'), name='uniq_brand_code_per_company', violation_error_message='A brand with this code already exists.')],
            },
        ),
    ]
