# Generated by Django 5.2.5 on 2026-09-22 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_branch_code_per_company'),
        ('core', '0005_user_employee'),
        ('fleet', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('want_approval', models.BooleanField(default=False)),
                ('approval_status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('vehicle_type_code', models.CharField(blank=True, max_length=20, verbose_name='Vehicle Type Code')),
                ('vehicle_type_name', models.CharField(max_length=100, verbose_name='Vehicle Type Name')),
                ('description', models.TextField(blank=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_types', to='fleet.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_types', to='fleet.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_types', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
            ],
            options={
                'db_table': 'vehicle_type',
                'ordering': ['vehicle_type_name'],
                'indexes': [models.Index(fields=['company'], name='vehicle_typ_company_a8625e_idx'), models.Index(fields=['category'], name='vehicle_typ_categor_65f031_idx'), models.Index(fields=['brand'], name='vehicle_typ_brand_i_4c7e2b_idx')],
            },
        ),
    ]
