# Generated by Django 5.2.5 on 2026-09-23 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_branch_code_per_company'),
        ('core', '0005_user_employee'),
        ('fleet', '0003_vehicletype'),
    ]

    operations = [
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('want_approval', models.BooleanField(default=False)),
                ('approval_status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('uom_code', models.CharField(max_length=20, verbose_name='UOM Code')),
                ('uom_name', models.CharField(max_length=100, verbose_name='UOM Name')),
                ('description', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uoms', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
            ],
            options={
                'verbose_name': 'UOM',
                'verbose_name_plural': 'UOMs',
                'db_table': 'uom',
                'ordering': ['uom_name'],
                'indexes': [models.Index(fields=['company'], name='uom_company_cbffe3_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'uom_code'), name='uniq_uom_code_per_company', violation_error_message='A UOM with this code already exists.')],
            },
        ),
    ]
