# Generated by Django 5.2.5 on 2026-09-23 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_branch_code_per_company'),
        ('core', '0005_user_employee'),
        ('crew', '0002_duty_roster'),
        ('fleet', '0005_assettype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('want_approval', models.BooleanField(default=False)),
                ('approval_status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('asset_code', models.CharField(max_length=30, verbose_name='Asset Code')),
                ('serial_no', models.CharField(blank=True, max_length=50, verbose_name='Serial No')),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('supplier', models.CharField(blank=True, max_length=150)),
                ('purchase_invoice_no', models.CharField(blank=True, max_length=50, verbose_name='Purchase Invoice No')),
                ('description', models.TextField(blank=True)),
                ('warranty_from_date', models.DateField(blank=True, null=True)),
                ('warranty_to_date', models.DateField(blank=True, null=True)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='fleet.assettype')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='company.branch')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='fleet.brand')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('custodian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodied_assets', to='crew.employee')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
            ],
            options={
                'db_table': 'asset',
                'ordering': ['asset_code'],
                'indexes': [models.Index(fields=['company'], name='asset_company_74aff9_idx'), models.Index(fields=['asset_type'], name='asset_asset_t_03945a_idx'), models.Index(fields=['brand'], name='asset_brand_i_cf0807_idx'), models.Index(fields=['custodian'], name='asset_custodi_bf8b61_idx'), models.Index(fields=['branch'], name='asset_branch__6b5fc7_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'asset_code'), name='uniq_asset_code_per_company', violation_error_message='An asset with this code already exists.')],
            },
        ),
    ]
