# Generated by Django 5.2.5 on 2026-09-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='other_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Other Tax'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='tax_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tax Percentage'),
        ),
    ]
