# Generated by Django 5.2.5 on 2026-09-24 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_weekday_monday_zero'),
        ('core', '0005_user_employee'),
        ('fleet', '0007_vehicletype_other_tax_vehicletype_tax_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('want_approval', models.BooleanField(default=False)),
                ('approval_status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('vehicle_code', models.CharField(max_length=30, verbose_name='Vehicle Code')),
                ('vehicle_name', models.CharField(max_length=100, verbose_name='Vehicle Name')),
                ('rfid_epc', models.CharField(max_length=64, verbose_name='RFID Tag EPC')),
                ('is_available', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='fleet.uom')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='fleet.vehicletype')),
            ],
            options={
                'db_table': 'vehicle',
                'ordering': ['vehicle_code'],
                'indexes': [models.Index(fields=['company'], name='vehicle_company_3c1663_idx'), models.Index(fields=['vehicle_type'], name='vehicle_vehicle_24f066_idx'), models.Index(fields=['uom'], name='vehicle_uom_id_5205b1_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'vehicle_code'), name='uniq_vehicle_code_per_company', violation_error_message='A vehicle with this code already exists.'), models.UniqueConstraint(fields=('company', 'rfid_epc'), name='uniq_vehicle_rfid_epc_per_company', violation_error_message='A vehicle with this RFID tag already exists.')],
            },
        ),
    ]
