# Generated by Django 5.2.5 on 2026-09-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_weekday_monday_zero'),
        ('core', '0005_user_employee'),
        ('fleet', '0008_vehicle'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vehicle',
            name='uniq_vehicle_rfid_epc_per_company',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='rfid_epc',
            field=models.CharField(blank=True, max_length=64, verbose_name='RFID Tag EPC'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('rfid_epc', ''), _negated=True), fields=('company', 'rfid_epc'), name='uniq_vehicle_rfid_epc_per_company', violation_error_message='A vehicle with this RFID tag already exists.'),
        ),
    ]
