# Generated by Django 5.2.5 on 2026-09-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0012_vehicle_identifier_vb'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='is_direct_rent',
            field=models.BooleanField(default=False, verbose_name='Direct Rent'),
        ),
    ]
